Part 4 – NumPy

In [15]:
import numpy as np

1) Create an array containing the numbers from 1 to 10.

In [16]:
numbers = np.arange(1, 11)

2) Print the array.

In [17]:
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


#3) Print its maximum and minimum value.


In [18]:
print(numbers.min())
print(numbers.max())

1
10


#4) Create an array of 5 zeros and print it.


In [19]:
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


#5) Create an array of 5 ones and print it.


In [20]:
ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


#6) Create an specific 2x3 matrix and print it.


In [21]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#7) Display the matrix.


In [22]:
print(matrix)

[[1 2 3]
 [4 5 6]]


#8) Use .shape to display its dimensions.


In [23]:
matrix.shape
print(matrix.shape)

(2, 3)
